"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'mr' | 'gu';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.userLogin': 'User Login',
    'nav.advocateLogin': 'Advocate Login',
    'nav.adminLogin': 'Admin Login',
    
    // Hero Section
    'hero.title': 'Advanced Arbitration & Legal Case Management',
    'hero.subtitle': 'Revolutionizing arbitration and legal case management with AI-powered solutions. Connect clients, advocates, and administrators in one comprehensive platform.',
    'hero.getStarted': 'Get Started',
    'hero.joinAdvocate': 'Join as Advocate',
    
    // Features
    'features.title': 'Powerful Features',
    'features.caseManagement': 'Case Management',
    'features.caseManagementDesc': 'Comprehensive case tracking and management system for all your legal matters.',
    'features.roleBased': 'Role-Based Access',
    'features.roleBasedDesc': 'Separate dashboards for users, advocates, and administrators with appropriate permissions.',
    'features.realtimeChat': 'Real-time Chat',
    'features.realtimeChatDesc': 'Instant communication between clients and advocates with file sharing capabilities.',
    'features.documentManagement': 'Document Management',
    'features.documentManagementDesc': 'Secure file upload and management with AWS S3 cloud storage integration.',
    'features.secure': 'Secure & Private',
    'features.secureDesc': 'Enterprise-grade security with JWT authentication and encrypted data storage.',
    'features.analytics': 'Analytics & Reports',
    'features.analyticsDesc': 'Comprehensive reporting and analytics for case progress and system insights.',
    
    // User Types
    'userTypes.title': 'Choose Your Role',
    'userTypes.forUsers': 'For Users',
    'userTypes.forUsersDesc': 'Submit and track your legal cases',
    'userTypes.forAdvocates': 'For Advocates',
    'userTypes.forAdvocatesDesc': 'Manage assigned cases and clients',
    'userTypes.forAdmins': 'For Administrators',
    'userTypes.forAdminsDesc': 'Oversee the entire system',
    
    // CTA
    'cta.title': 'Ready to Get Started?',
    'cta.subtitle': 'Join thousands of legal professionals who trust our platform for their case management needs.',
    'cta.startTrial': 'Start Free Trial',
    'cta.becomeAdvocate': 'Become an Advocate',
    
    // Footer
    'footer.description': 'Advanced arbitration and legal case management platform with AI-powered solutions and multi-language support.',
    'footer.quickLinks': 'Quick Links',
    'footer.copyright': '© 2024 ARBITALK. All rights reserved.',
    
    // About Page
    'about.title': 'About ARBITALK',
    'about.subtitle': 'Revolutionizing arbitration and legal case management through innovative technology, artificial intelligence, and multi-language accessibility across India.',
    'about.mission': 'Our Mission',
    'about.missionTitle': 'Democratizing Legal Access',
    'about.missionDesc1': 'ARBITALK was founded with the vision to make arbitration and legal case management accessible to everyone across India. We believe that language barriers and technological complexity should never prevent access to justice.',
    'about.missionDesc2': 'Our platform combines cutting-edge AI technology with user-friendly design to streamline arbitration processes, reduce costs, and improve outcomes for all parties involved.',
    
    // Contact Page
    'contact.title': 'Contact ARBITALK',
    'contact.subtitle': 'Get in touch with our team for support, inquiries, or to learn more about our arbitration and legal case management platform.',
    'contact.sendMessage': 'Send us a Message',
    'contact.fullName': 'Full Name',
    'contact.email': 'Email Address',
    'contact.phone': 'Phone Number',
    'contact.userType': 'User Type',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    
    // Dashboard
    'dashboard.title': 'My Dashboard',
    'dashboard.subtitle': 'Welcome back! Here\'s an overview of your legal cases and recent activity.',
    'dashboard.totalCases': 'Total Cases',
    'dashboard.activeCases': 'Active Cases',
    'dashboard.closedCases': 'Closed Cases',
    'dashboard.pendingCases': 'Pending Cases',
    'dashboard.recentCases': 'My Recent Cases',
    'dashboard.viewAllCases': 'View All Cases',
    'dashboard.caseTitle': 'Case Title',
    'dashboard.advocate': 'Advocate',
    'dashboard.status': 'Status',
    'dashboard.priority': 'Priority',
    'dashboard.created': 'Created',
    'dashboard.actions': 'Actions',
    'dashboard.viewDetails': 'View Details',
    'dashboard.chat': 'Chat',
    'dashboard.addCase': 'Add Case',
    
    // Cases Page
    'cases.title': 'My Cases',
    'cases.search': 'Search cases...',
    'cases.status': 'Status',
    'cases.type': 'Type',
    'cases.priority': 'Priority',
    'cases.refresh': 'Refresh',
    'cases.noCases': 'No cases found',
    'cases.loading': 'Loading cases...',
    
    // Case Details Modal
    'caseDetails.title': 'Case Details',
    'caseDetails.caseInformation': 'Case Information',
    'caseDetails.caseNumber': 'Case Number',
    'caseDetails.description': 'Description',
    'caseDetails.courtName': 'Court Name',
    'caseDetails.judgeName': 'Judge Name',
    'caseDetails.nextHearingDate': 'Next Hearing Date',
    'caseDetails.startDate': 'Start Date',
    'caseDetails.endDate': 'End Date',
    'caseDetails.updatedAt': 'Updated At',
    'caseDetails.financialInformation': 'Financial Information',
    'caseDetails.totalFees': 'Total Fees',
    'caseDetails.feesPaid': 'Fees Paid',
    'caseDetails.outstandingAmount': 'Outstanding Amount',
    'caseDetails.disputeInformation': 'Dispute Information',
    'caseDetails.requestingParty': 'Requesting Party',
    'caseDetails.respondent': 'Respondent',
    'caseDetails.disputeDetails': 'Dispute Details',
    'caseDetails.name': 'Name',
    'caseDetails.email': 'Email',
    'caseDetails.phone': 'Phone',
    'caseDetails.address': 'Address',
    'caseDetails.relationshipBetweenParties': 'Relationship Between Parties',
    'caseDetails.natureOfDispute': 'Nature of Dispute',
    'caseDetails.briefDescription': 'Brief Description',
    'caseDetails.occurrenceDate': 'Occurrence Date',
    'caseDetails.priorCommunication': 'Prior Communication',
    'caseDetails.reliefSought': 'Relief Sought',
    'caseDetails.monetaryClaim': 'Monetary Claim',
    'caseDetails.settlement': 'Settlement',
    'caseDetails.otherRelief': 'Other Relief',
    'caseDetails.otherReliefDetails': 'Other Relief Details',
    'caseDetails.yes': 'Yes',
    'caseDetails.no': 'No',
    'caseDetails.none': 'None',
    'caseDetails.caseTeam': 'Case Team',
    'caseDetails.client': 'Client',
    'caseDetails.advocate': 'Advocate',
    'caseDetails.attachments': 'Attachments',
    'caseDetails.noAttachments': 'No attachments',
    'caseDetails.close': 'Close',
    'caseDetails.chatWithAdvocate': 'Chat with Advocate',
    
    // Create Case Page
    'createCase.title': 'Create New Case',
    'createCase.disputeResolutionApplication': 'Dispute Resolution Application',
    'createCase.caseInformation': 'Case Information',
    'createCase.caseTitle': 'Case Title',
    'createCase.caseDescription': 'Case Description',
    'createCase.requestingParty': 'Requesting Party',
    'createCase.oppositeParty': 'Opposite Party (Respondent)',
    'createCase.disputeDetails': 'Dispute Details',
    'createCase.fullName': 'Full Name of Requesting Party',
    'createCase.email': 'Email id',
    'createCase.mobileNumber': 'Mobile Number (WhatsApp preferable)',
    'createCase.address': 'Registered Business Address',
    'createCase.fullNameOfOppositeParty': 'Full Name of Opposite Party',
    'createCase.contactNumberOfRespondent': 'Contact number of Respondent',
    'createCase.emailOfRespondent': 'Email id of Respondent',
    'createCase.addressOfRespondent': 'Registered Business Address of Respondent',
    'createCase.relationshipBetweenParties': 'Relationship between parties',
    'createCase.natureOfDispute': 'Nature of Dispute',
    'createCase.client': 'Client',
    'createCase.vendor': 'Vendor',
    'createCase.businesspartner': 'Business Partner',
    'createCase.employee': 'Employee',
    'createCase.employer': 'Employer',
    'createCase.family': 'Family',
    'createCase.submit': 'Submit',
    'createCase.submitting': 'Submitting...',
    'createCase.cancel': 'Cancel',
    'createCase.caseCreatedSuccessfully': 'Case created successfully',
    
    // Chat Module
    'chat.title': 'Case Chat',
    'chat.searchCases': 'Search cases...',
    'chat.status': 'Status',
    'chat.allStatuses': 'All Statuses',
    'chat.open': 'Open',
    'chat.inProgress': 'In Progress',
    'chat.onHold': 'On Hold',
    'chat.closed': 'Closed',
    'chat.createNewCase': 'Create New Case',
    'chat.notAssigned': 'Not Assigned',
    'chat.noCasesFound': 'No cases found',
    'chat.noCasesYet': 'No cases yet',
    'chat.tryDifferentSearch': 'Try different search criteria',
    'chat.createFirstCase': 'Create your first case to get started',
    
    // Admin Chat specific
    'chat.adminTitle': 'Admin Chat Management',
    'chat.allAdvocates': 'All Advocates',
    'chat.unassigned': 'Unassigned',
    'chat.manageCases': 'Manage Cases',
    'chat.noCasesInSystem': 'No cases in the system yet',
    'chat.assignCase': 'Assign Case',
    'chat.assignCaseTo': 'Assign case to advocate',
    'chat.selectAdvocate': 'Select Advocate',
    'chat.assigning': 'Assigning...',
    'chat.assign': 'Assign',
    'chat.adminChat': 'Admin Chat',
    'chat.client': 'Client',
    'chat.advocate': 'Advocate',
    'chat.connected': 'Connected',
    'chat.disconnected': 'Disconnected',
    'chat.noMessagesYet': 'No messages yet',
    'chat.startConversation': 'Start the conversation by sending a message',
    'chat.typeMessage': 'Type your message...',
    'chat.send': 'Send',
    'chat.uploadFile': 'Upload File',
    'chat.selected': 'Selected',
    'chat.uploading': 'Uploading...',
    'chat.upload': 'Upload',
    
    // Advocate Chat specific
    'chat.advocateTitle': 'Advocate Chat',
    'chat.viewAllCases': 'View All Cases',
    'chat.noAssignedCases': 'No assigned cases yet',
    'chat.waitForAssignment': 'Wait for admin to assign cases to you',
    
    // Cases page translations
    'cases.assignedCases': 'Assigned Cases',
    'cases.searchCases': 'Search cases...',
    'cases.allStatuses': 'All Statuses',
    'cases.goToChat': 'Go to Chat',
    'cases.caseNumber': 'Case Number',
    'cases.caseTitle': 'Title',
    'cases.client': 'Client',
    'cases.created': 'Created',
    'cases.actions': 'Actions',
    'cases.viewDetails': 'View Details',
    'cases.chat': 'Chat',
  },
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.about': 'हमारे बारे में',
    'nav.contact': 'संपर्क',
    'nav.userLogin': 'उपयोगकर्ता लॉगिन',
    'nav.advocateLogin': 'वकील लॉगिन',
    'nav.adminLogin': 'एडमिन लॉगिन',
    
    // Hero Section
    'hero.title': 'उन्नत मध्यस्थता और कानूनी मामला प्रबंधन',
    'hero.subtitle': 'AI-संचालित समाधानों के साथ मध्यस्थता और कानूनी मामला प्रबंधन में क्रांति। ग्राहकों, वकीलों और प्रशासकों को एक व्यापक प्लेटफॉर्म में जोड़ें।',
    'hero.getStarted': 'शुरू करें',
    'hero.joinAdvocate': 'वकील के रूप में जुड़ें',
    
    // Features
    'features.title': 'शक्तिशाली सुविधाएं',
    'features.caseManagement': 'मामला प्रबंधन',
    'features.caseManagementDesc': 'आपके सभी कानूनी मामलों के लिए व्यापक मामला ट्रैकिंग और प्रबंधन प्रणाली।',
    'features.roleBased': 'भूमिका-आधारित पहुंच',
    'features.roleBasedDesc': 'उपयुक्त अनुमतियों के साथ उपयोगकर्ताओं, वकीलों और प्रशासकों के लिए अलग डैशबोर्ड।',
    'features.realtimeChat': 'रियल-टाइम चैट',
    'features.realtimeChatDesc': 'फ़ाइल साझाकरण क्षमताओं के साथ ग्राहकों और वकीलों के बीच तत्काल संचार।',
    'features.documentManagement': 'दस्तावेज़ प्रबंधन',
    'features.documentManagementDesc': 'AWS S3 क्लाउड स्टोरेज एकीकरण के साथ सुरक्षित फ़ाइल अपलोड और प्रबंधन।',
    'features.secure': 'सुरक्षित और निजी',
    'features.secureDesc': 'JWT प्रमाणीकरण और एन्क्रिप्टेड डेटा स्टोरेज के साथ एंटरप्राइज़-ग्रेड सुरक्षा।',
    'features.analytics': 'विश्लेषण और रिपोर्ट',
    'features.analyticsDesc': 'मामला प्रगति और सिस्टम अंतर्दृष्टि के लिए व्यापक रिपोर्टिंग और विश्लेषण।',
    
    // User Types
    'userTypes.title': 'अपनी भूमिका चुनें',
    'userTypes.forUsers': 'उपयोगकर्ताओं के लिए',
    'userTypes.forUsersDesc': 'अपने कानूनी मामलों को जमा करें और ट्रैक करें',
    'userTypes.forAdvocates': 'वकीलों के लिए',
    'userTypes.forAdvocatesDesc': 'निर्दिष्ट मामलों और ग्राहकों का प्रबंधन करें',
    'userTypes.forAdmins': 'प्रशासकों के लिए',
    'userTypes.forAdminsDesc': 'पूरे सिस्टम की देखरेख करें',
    
    // CTA
    'cta.title': 'शुरू करने के लिए तैयार हैं?',
    'cta.subtitle': 'हजारों कानूनी पेशेवरों में शामिल हों जो अपनी मामला प्रबंधन आवश्यकताओं के लिए हमारे प्लेटफॉर्म पर भरोसा करते हैं।',
    'cta.startTrial': 'मुफ्त ट्रायल शुरू करें',
    'cta.becomeAdvocate': 'वकील बनें',
    
    // Footer
    'footer.description': 'AI-संचालित समाधानों और बहु-भाषा समर्थन के साथ उन्नत मध्यस्थता और कानूनी मामला प्रबंधन प्लेटफॉर्म।',
    'footer.quickLinks': 'त्वरित लिंक',
    'footer.copyright': '© 2024 ARBITALK। सभी अधिकार सुरक्षित।',
    
    // About Page
    'about.title': 'ARBITALK के बारे में',
    'about.subtitle': 'भारत भर में नवीन प्रौद्योगिकी, कृत्रिम बुद्धिमत्ता और बहु-भाषा पहुंच के माध्यम से मध्यस्थता और कानूनी मामला प्रबंधन में क्रांति।',
    'about.mission': 'हमारा मिशन',
    'about.missionTitle': 'कानूनी पहुंच का लोकतंत्रीकरण',
    'about.missionDesc1': 'ARBITALK की स्थापना भारत भर में सभी के लिए मध्यस्थता और कानूनी मामला प्रबंधन को सुलभ बनाने के दृष्टिकोण के साथ की गई थी। हम मानते हैं कि भाषा बाधाएं और तकनीकी जटिलता कभी भी न्याय तक पहुंच को रोकनी नहीं चाहिए।',
    'about.missionDesc2': 'हमारा प्लेटफॉर्म मध्यस्थता प्रक्रियाओं को सुव्यवस्थित करने, लागत कम करने और सभी पक्षों के लिए परिणामों में सुधार करने के लिए अत्याधुनिक AI प्रौद्योगिकी को उपयोगकर्ता-अनुकूल डिज़ाइन के साथ जोड़ता है।',
    
    // Contact Page
    'contact.title': 'ARBITALK से संपर्क करें',
    'contact.subtitle': 'सहायता, पूछताछ के लिए या हमारे मध्यस्थता और कानूनी मामला प्रबंधन प्लेटफॉर्म के बारे में अधिक जानने के लिए हमारी टीम से संपर्क करें।',
    'contact.sendMessage': 'हमें एक संदेश भेजें',
    'contact.fullName': 'पूरा नाम',
    'contact.email': 'ईमेल पता',
    'contact.phone': 'फोन नंबर',
    'contact.userType': 'उपयोगकर्ता प्रकार',
    'contact.subject': 'विषय',
    'contact.message': 'संदेश',
    'contact.send': 'संदेश भेजें',
    'contact.sending': 'भेज रहे हैं...',
    
    // Dashboard
    'dashboard.title': 'मेरा डैशबोर्ड',
    'dashboard.subtitle': 'वापस स्वागत है! यहाँ आपके कानूनी मामलों और हाल की गतिविधि का अवलोकन है।',
    'dashboard.totalCases': 'कुल मामले',
    'dashboard.activeCases': 'सक्रिय मामले',
    'dashboard.closedCases': 'बंद मामले',
    'dashboard.pendingCases': 'लंबित मामले',
    'dashboard.recentCases': 'मेरे हाल के मामले',
    'dashboard.viewAllCases': 'सभी मामले देखें',
    'dashboard.caseTitle': 'मामले का शीर्षक',
    'dashboard.advocate': 'वकील',
    'dashboard.status': 'स्थिति',
    'dashboard.priority': 'प्राथमिकता',
    'dashboard.created': 'बनाया गया',
    'dashboard.actions': 'कार्य',
    'dashboard.viewDetails': 'विवरण देखें',
    'dashboard.chat': 'चैट',
    'dashboard.addCase': 'मामला जोड़ें',
    
    // Cases Page
    'cases.title': 'मेरे मामले',
    'cases.search': 'मामले खोजें...',
    'cases.status': 'स्थिति',
    'cases.type': 'प्रकार',
    'cases.priority': 'प्राथमिकता',
    'cases.refresh': 'रिफ्रेश करें',
    'cases.noCases': 'कोई मामला नहीं मिला',
    'cases.loading': 'मामले लोड हो रहे हैं...',
    
    // Case Details Modal
    'caseDetails.title': 'मामले का विवरण',
    'caseDetails.caseInformation': 'मामले की जानकारी',
    'caseDetails.caseNumber': 'मामला संख्या',
    'caseDetails.description': 'विवरण',
    'caseDetails.courtName': 'न्यायालय का नाम',
    'caseDetails.judgeName': 'न्यायाधीश का नाम',
    'caseDetails.nextHearingDate': 'अगली सुनवाई की तारीख',
    'caseDetails.startDate': 'प्रारंभ तिथि',
    'caseDetails.endDate': 'समाप्ति तिथि',
    'caseDetails.updatedAt': 'अपडेट किया गया',
    'caseDetails.financialInformation': 'वित्तीय जानकारी',
    'caseDetails.totalFees': 'कुल शुल्क',
    'caseDetails.feesPaid': 'भुगतान किया गया शुल्क',
    'caseDetails.outstandingAmount': 'बकाया राशि',
    'caseDetails.disputeInformation': 'विवाद की जानकारी',
    'caseDetails.requestingParty': 'अनुरोध करने वाला पक्ष',
    'caseDetails.respondent': 'प्रतिवादी',
    'caseDetails.disputeDetails': 'विवाद का विवरण',
    'caseDetails.name': 'नाम',
    'caseDetails.email': 'ईमेल',
    'caseDetails.phone': 'फोन',
    'caseDetails.address': 'पता',
    'caseDetails.relationshipBetweenParties': 'पक्षों के बीच संबंध',
    'caseDetails.natureOfDispute': 'विवाद की प्रकृति',
    'caseDetails.briefDescription': 'संक्षिप्त विवरण',
    'caseDetails.occurrenceDate': 'घटना की तिथि',
    'caseDetails.priorCommunication': 'पूर्व संचार',
    'caseDetails.reliefSought': 'मांगा गया राहत',
    'caseDetails.monetaryClaim': 'मौद्रिक दावा',
    'caseDetails.settlement': 'समझौता',
    'caseDetails.otherRelief': 'अन्य राहत',
    'caseDetails.otherReliefDetails': 'अन्य राहत विवरण',
    'caseDetails.yes': 'हाँ',
    'caseDetails.no': 'नहीं',
    'caseDetails.none': 'कोई नहीं',
    'caseDetails.caseTeam': 'मामले की टीम',
    'caseDetails.client': 'ग्राहक',
    'caseDetails.advocate': 'वकील',
    'caseDetails.attachments': 'संलग्नक',
    'caseDetails.noAttachments': 'कोई संलग्नक नहीं',
    'caseDetails.close': 'बंद करें',
    'caseDetails.chatWithAdvocate': 'वकील से चैट करें',
    
    // Create Case Page
    'createCase.title': 'नया मामला बनाएं',
    'createCase.disputeResolutionApplication': 'विवाद समाधान आवेदन',
    'createCase.caseInformation': 'मामले की जानकारी',
    'createCase.caseTitle': 'मामले का शीर्षक',
    'createCase.caseDescription': 'मामले का विवरण',
    'createCase.requestingParty': 'अनुरोध करने वाला पक्ष',
    'createCase.oppositeParty': 'विपरीत पक्ष (प्रतिवादी)',
    'createCase.disputeDetails': 'विवाद का विवरण',
    'createCase.fullName': 'अनुरोध करने वाले पक्ष का पूरा नाम',
    'createCase.email': 'ईमेल आईडी',
    'createCase.mobileNumber': 'मोबाइल नंबर (व्हाट्सऐप पसंदीदा)',
    'createCase.address': 'पंजीकृत व्यापारिक पता',
    'createCase.fullNameOfOppositeParty': 'विपरीत पक्ष का पूरा नाम',
    'createCase.contactNumberOfRespondent': 'प्रतिवादी का संपर्क नंबर',
    'createCase.emailOfRespondent': 'प्रतिवादी का ईमेल आईडी',
    'createCase.addressOfRespondent': 'प्रतिवादी का पंजीकृत व्यापारिक पता',
    'createCase.relationshipBetweenParties': 'पक्षों के बीच संबंध',
    'createCase.natureOfDispute': 'विवाद की प्रकृति',
    'createCase.client': 'ग्राहक',
    'createCase.vendor': 'विक्रेता',
    'createCase.businesspartner': 'व्यापारिक साझेदार',
    'createCase.employee': 'कर्मचारी',
    'createCase.employer': 'नियोक्ता',
    'createCase.family': 'परिवार',
    'createCase.submit': 'जमा करें',
    'createCase.submitting': 'जमा कर रहे हैं...',
    'createCase.cancel': 'रद्द करें',
    'createCase.caseCreatedSuccessfully': 'मामला सफलतापूर्वक बनाया गया',
    
    // Chat Module
    'chat.title': 'केस चैट',
    'chat.searchCases': 'केस खोजें...',
    'chat.status': 'स्थिति',
    'chat.allStatuses': 'सभी स्थितियां',
    'chat.open': 'खुला',
    'chat.inProgress': 'प्रगति में',
    'chat.onHold': 'रोक दिया गया',
    'chat.closed': 'बंद',
    'chat.createNewCase': 'नया केस बनाएं',
    'chat.notAssigned': 'असाइन नहीं किया गया',
    'chat.noCasesFound': 'कोई केस नहीं मिला',
    'chat.noCasesYet': 'अभी तक कोई केस नहीं',
    'chat.tryDifferentSearch': 'अलग खोज मानदंड आज़माएं',
    'chat.createFirstCase': 'शुरू करने के लिए अपना पहला केस बनाएं',
    
    // Admin Chat specific
    'chat.adminTitle': 'एडमिन चैट प्रबंधन',
    'chat.allAdvocates': 'सभी वकील',
    'chat.unassigned': 'असाइन नहीं',
    'chat.manageCases': 'केस प्रबंधन',
    'chat.noCasesInSystem': 'अभी तक सिस्टम में कोई केस नहीं',
    'chat.assignCase': 'केस असाइन करें',
    'chat.assignCaseTo': 'केस को वकील को असाइन करें',
    'chat.selectAdvocate': 'वकील चुनें',
    'chat.assigning': 'असाइन कर रहे हैं...',
    'chat.assign': 'असाइन करें',
    'chat.adminChat': 'एडमिन चैट',
    'chat.client': 'क्लाइंट',
    'chat.advocate': 'वकील',
    'chat.connected': 'जुड़ा हुआ',
    'chat.disconnected': 'डिस्कनेक्ट',
    'chat.noMessagesYet': 'अभी तक कोई संदेश नहीं',
    'chat.startConversation': 'संदेश भेजकर बातचीत शुरू करें',
    'chat.typeMessage': 'अपना संदेश टाइप करें...',
    'chat.send': 'भेजें',
    'chat.uploadFile': 'फ़ाइल अपलोड करें',
    'chat.selected': 'चयनित',
    'chat.uploading': 'अपलोड हो रहा है...',
    'chat.upload': 'अपलोड',
    
    // Advocate Chat specific
    'chat.advocateTitle': 'वकील चैट',
    'chat.viewAllCases': 'सभी केस देखें',
    'chat.noAssignedCases': 'अभी तक कोई असाइन केस नहीं',
    'chat.waitForAssignment': 'एडमिन द्वारा आपको केस असाइन करने की प्रतीक्षा करें',
    
    // Cases page translations
    'cases.assignedCases': 'असाइन केस',
    'cases.searchCases': 'केस खोजें...',
    'cases.allStatuses': 'सभी स्थितियां',
    'cases.goToChat': 'चैट पर जाएं',
    'cases.caseNumber': 'केस नंबर',
    'cases.caseTitle': 'शीर्षक',
    'cases.client': 'क्लाइंट',
    'cases.created': 'बनाया गया',
    'cases.actions': 'कार्य',
    'cases.viewDetails': 'विवरण देखें',
    'cases.chat': 'चैट',
  },
  mr: {
    // Navigation
    'nav.home': 'मुख्यपृष्ठ',
    'nav.about': 'आमच्या बद्दल',
    'nav.contact': 'संपर्क',
    'nav.userLogin': 'वापरकर्ता लॉगिन',
    'nav.advocateLogin': 'वकील लॉगिन',
    'nav.adminLogin': 'एडमिन लॉगिन',
    
    // Hero Section
    'hero.title': 'प्रगत मध्यस्थता आणि कायदेशीर केस व्यवस्थापन',
    'hero.subtitle': 'AI-चालित उपायांसह मध्यस्थता आणि कायदेशीर केस व्यवस्थापनात क्रांती. ग्राहक, वकील आणि प्रशासकांना एका व्यापक प्लॅटफॉर्ममध्ये जोडा.',
    'hero.getStarted': 'सुरु करा',
    'hero.joinAdvocate': 'वकील म्हणून सामील व्हा',
    
    // Features
    'features.title': 'शक्तिशाली वैशिष्ट्ये',
    'features.caseManagement': 'केस व्यवस्थापन',
    'features.caseManagementDesc': 'तुमच्या सर्व कायदेशीर बाबींसाठी व्यापक केस ट्रॅकिंग आणि व्यवस्थापन प्रणाली.',
    'features.roleBased': 'भूमिका-आधारित प्रवेश',
    'features.roleBasedDesc': 'योग्य परवानग्यांसह वापरकर्ते, वकील आणि प्रशासकांसाठी वेगळे डॅशबोर्ड.',
    'features.realtimeChat': 'रिअल-टाइम चॅट',
    'features.realtimeChatDesc': 'फाइल शेअरिंग क्षमतांसह ग्राहक आणि वकीलांमधील तत्काळ संप्रेषण.',
    'features.documentManagement': 'दस्तावेज व्यवस्थापन',
    'features.documentManagementDesc': 'AWS S3 क्लाउड स्टोरेज एकीकरणासह सुरक्षित फाइल अपलोड आणि व्यवस्थापन.',
    'features.secure': 'सुरक्षित आणि खाजगी',
    'features.secureDesc': 'JWT प्रमाणीकरण आणि एन्क्रिप्टेड डेटा स्टोरेजसह एंटरप्राइझ-ग्रेड सुरक्षा.',
    'features.analytics': 'विश्लेषण आणि अहवाल',
    'features.analyticsDesc': 'केस प्रगती आणि सिस्टम अंतर्दृष्टीसाठी व्यापक अहवाल आणि विश्लेषण.',
    
    // User Types
    'userTypes.title': 'तुमची भूमिका निवडा',
    'userTypes.forUsers': 'वापरकर्त्यांसाठी',
    'userTypes.forUsersDesc': 'तुमचे कायदेशीर केस सबमिट करा आणि ट्रॅक करा',
    'userTypes.forAdvocates': 'वकीलांसाठी',
    'userTypes.forAdvocatesDesc': 'नियुक्त केलेल्या केसेस आणि ग्राहकांचे व्यवस्थापन करा',
    'userTypes.forAdmins': 'प्रशासकांसाठी',
    'userTypes.forAdminsDesc': 'संपूर्ण सिस्टमचे निरीक्षण करा',
    
    // CTA
    'cta.title': 'सुरु करण्यासाठी तयार आहात?',
    'cta.subtitle': 'हजारो कायदेशीर व्यावसायिकांमध्ये सामील व्हा जे त्यांच्या केस व्यवस्थापन गरजांसाठी आमच्या प्लॅटफॉर्मवर विश्वास ठेवतात.',
    'cta.startTrial': 'मोफत ट्रायल सुरु करा',
    'cta.becomeAdvocate': 'वकील बना',
    
    // Footer
    'footer.description': 'AI-चालित उपाय आणि बहु-भाषा समर्थनासह प्रगत मध्यस्थता आणि कायदेशीर केस व्यवस्थापन प्लॅटफॉर्म.',
    'footer.quickLinks': 'द्रुत दुवे',
    'footer.copyright': '© 2024 ARBITALK. सर्व हक्क सुरक्षित.',
    
    // About Page
    'about.title': 'ARBITALK बद्दल',
    'about.subtitle': 'भारतभर नवीन तंत्रज्ञान, कृत्रिम बुद्धिमत्ता आणि बहु-भाषा प्रवेशाद्वारे मध्यस्थता आणि कायदेशीर केस व्यवस्थापनात क्रांती.',
    'about.mission': 'आमचे मिशन',
    'about.missionTitle': 'कायदेशीर प्रवेशाचे लोकशाहीकरण',
    'about.missionDesc1': 'ARBITALK ची स्थापना भारतभर सर्वांसाठी मध्यस्थता आणि कायदेशीर केस व्यवस्थापन सुलभ करण्याच्या दृष्टीकोनातून केली गेली. आम्ही मानतो की भाषा अडथळे आणि तांत्रिक जटिलता कधीही न्यायापर्यंत पोहोचण्यास प्रतिबंध करू नये.',
    'about.missionDesc2': 'आमचे प्लॅटफॉर्म मध्यस्थता प्रक्रिया सुव्यवस्थित करण्यासाठी, खर्च कमी करण्यासाठी आणि सर्व पक्षांच्या परिणामांमध्ये सुधारणा करण्यासाठी अत्याधुनिक AI तंत्रज्ञानाला वापरकर्ता-अनुकूल डिझाइनसह जोडते.',
    
    // Contact Page
    'contact.title': 'ARBITALK शी संपर्क साधा',
    'contact.subtitle': 'सहाय्य, चौकशी किंवा आमच्या मध्यस्थता आणि कायदेशीर केस व्यवस्थापन प्लॅटफॉर्मबद्दल अधिक जाणून घेण्यासाठी आमच्या टीमशी संपर्क साधा.',
    'contact.sendMessage': 'आम्हाला एक संदेश पाठवा',
    'contact.fullName': 'पूर्ण नाव',
    'contact.email': 'ईमेल पत्ता',
    'contact.phone': 'फोन नंबर',
    'contact.userType': 'वापरकर्ता प्रकार',
    'contact.subject': 'विषय',
    'contact.message': 'संदेश',
    'contact.send': 'संदेश पाठवा',
    'contact.sending': 'पाठवत आहे...',
    
    // Dashboard
    'dashboard.title': 'माझे डॅशबोर्ड',
    'dashboard.subtitle': 'परत स्वागत! येथे तुमच्या कायदेशीर केसेस आणि अलीकडील क्रियाकलापांचा आढावा आहे.',
    'dashboard.totalCases': 'एकूण केसेस',
    'dashboard.activeCases': 'सक्रिय केसेस',
    'dashboard.closedCases': 'बंद केसेस',
    'dashboard.pendingCases': 'प्रलंबित केसेस',
    'dashboard.recentCases': 'माझे अलीकडील केसेस',
    'dashboard.viewAllCases': 'सर्व केसेस पहा',
    'dashboard.caseTitle': 'केस शीर्षक',
    'dashboard.advocate': 'वकील',
    'dashboard.status': 'स्थिती',
    'dashboard.priority': 'प्राधान्य',
    'dashboard.created': 'तयार केले',
    'dashboard.actions': 'क्रिया',
    'dashboard.viewDetails': 'तपशील पहा',
    'dashboard.chat': 'चॅट',
    'dashboard.addCase': 'केस जोडा',
    
    // Cases Page
    'cases.title': 'माझे केसेस',
    'cases.search': 'केसेस शोधा...',
    'cases.status': 'स्थिती',
    'cases.type': 'प्रकार',
    'cases.priority': 'प्राधान्य',
    'cases.refresh': 'रिफ्रेश करा',
    'cases.noCases': 'कोणतेही केसेस सापडले नाही',
    'cases.loading': 'केसेस लोड होत आहेत...',
    
    // Case Details Modal
    'caseDetails.title': 'केस तपशील',
    'caseDetails.caseInformation': 'केस माहिती',
    'caseDetails.caseNumber': 'केस क्रमांक',
    'caseDetails.description': 'वर्णन',
    'caseDetails.courtName': 'न्यायालयाचे नाव',
    'caseDetails.judgeName': 'न्यायाधीशाचे नाव',
    'caseDetails.nextHearingDate': 'पुढील सुनावणीची तारीख',
    'caseDetails.startDate': 'सुरुवातीची तारीख',
    'caseDetails.endDate': 'समाप्तीची तारीख',
    'caseDetails.updatedAt': 'अपडेट केले',
    'caseDetails.financialInformation': 'आर्थिक माहिती',
    'caseDetails.totalFees': 'एकूण फी',
    'caseDetails.feesPaid': 'दिलेली फी',
    'caseDetails.outstandingAmount': 'बाकी रक्कम',
    'caseDetails.disputeInformation': 'विवाद माहिती',
    'caseDetails.requestingParty': 'विनंती करणारा पक्ष',
    'caseDetails.respondent': 'प्रतिवादी',
    'caseDetails.disputeDetails': 'विवाद तपशील',
    'caseDetails.name': 'नाव',
    'caseDetails.email': 'ईमेल',
    'caseDetails.phone': 'फोन',
    'caseDetails.address': 'पत्ता',
    'caseDetails.relationshipBetweenParties': 'पक्षांमधील नाते',
    'caseDetails.natureOfDispute': 'विवादाचे स्वरूप',
    'caseDetails.briefDescription': 'संक्षिप्त वर्णन',
    'caseDetails.occurrenceDate': 'घटनेची तारीख',
    'caseDetails.priorCommunication': 'पूर्व संप्रेषण',
    'caseDetails.reliefSought': 'मागितलेली मदत',
    'caseDetails.monetaryClaim': 'आर्थिक दावा',
    'caseDetails.settlement': 'समझौता',
    'caseDetails.otherRelief': 'इतर मदत',
    'caseDetails.otherReliefDetails': 'इतर मदत तपशील',
    'caseDetails.yes': 'होय',
    'caseDetails.no': 'नाही',
    'caseDetails.none': 'काही नाही',
    'caseDetails.caseTeam': 'केस टीम',
    'caseDetails.client': 'ग्राहक',
    'caseDetails.advocate': 'वकील',
    'caseDetails.attachments': 'संलग्नक',
    'caseDetails.noAttachments': 'कोणतेही संलग्नक नाही',
    'caseDetails.close': 'बंद करा',
    'caseDetails.chatWithAdvocate': 'वकीलाशी चॅट करा',
    
    // Create Case Page
    'createCase.title': 'नवीन केस तयार करा',
    'createCase.disputeResolutionApplication': 'विवाद निराकरण अर्ज',
    'createCase.caseInformation': 'केस माहिती',
    'createCase.caseTitle': 'केस शीर्षक',
    'createCase.caseDescription': 'केस वर्णन',
    'createCase.requestingParty': 'विनंती करणारा पक्ष',
    'createCase.oppositeParty': 'विरुद्ध पक्ष (प्रतिवादी)',
    'createCase.disputeDetails': 'विवाद तपशील',
    'createCase.fullName': 'विनंती करणाऱ्या पक्षाचे पूर्ण नाव',
    'createCase.email': 'ईमेल आयडी',
    'createCase.mobileNumber': 'मोबाइल नंबर (व्हाट्सऍप प्राधान्य)',
    'createCase.address': 'नोंदणीकृत व्यापारी पत्ता',
    'createCase.fullNameOfOppositeParty': 'विरुद्ध पक्षाचे पूर्ण नाव',
    'createCase.contactNumberOfRespondent': 'प्रतिवादीचा संपर्क नंबर',
    'createCase.emailOfRespondent': 'प्रतिवादीचा ईमेल आयडी',
    'createCase.addressOfRespondent': 'प्रतिवादीचा नोंदणीकृत व्यापारी पत्ता',
    'createCase.relationshipBetweenParties': 'पक्षांमधील नाते',
    'createCase.natureOfDispute': 'विवादाचे स्वरूप',
    'createCase.client': 'ग्राहक',
    'createCase.vendor': 'विक्रेता',
    'createCase.businesspartner': 'व्यापारी भागीदार',
    'createCase.employee': 'कर्मचारी',
    'createCase.employer': 'नियोक्ता',
    'createCase.family': 'कुटुंब',
    'createCase.submit': 'सबमिट करा',
    'createCase.submitting': 'सबमिट करत आहे...',
    'createCase.cancel': 'रद्द करा',
    'createCase.caseCreatedSuccessfully': 'केस यशस्वीरित्या तयार केला',
    
    // Chat Module
    'chat.title': 'केस चॅट',
    'chat.searchCases': 'केस शोधा...',
    'chat.status': 'स्थिती',
    'chat.allStatuses': 'सर्व स्थिती',
    'chat.open': 'उघडे',
    'chat.inProgress': 'प्रगतीत',
    'chat.onHold': 'थांबवले',
    'chat.closed': 'बंद',
    'chat.createNewCase': 'नवीन केस तयार करा',
    'chat.notAssigned': 'नियुक्त नाही',
    'chat.noCasesFound': 'कोणतेही केस सापडले नाही',
    'chat.noCasesYet': 'अद्याप कोणतेही केस नाही',
    'chat.tryDifferentSearch': 'वेगवेगळे शोध निकष वापरा',
    'chat.createFirstCase': 'सुरुवात करण्यासाठी आपला पहिला केस तयार करा',
    
    // Admin Chat specific
    'chat.adminTitle': 'एडमिन चॅट व्यवस्थापन',
    'chat.allAdvocates': 'सर्व वकील',
    'chat.unassigned': 'नियुक्त नाही',
    'chat.manageCases': 'केस व्यवस्थापन',
    'chat.noCasesInSystem': 'अद्याप सिस्टममध्ये कोणतेही केस नाही',
    'chat.assignCase': 'केस नियुक्त करा',
    'chat.assignCaseTo': 'केस वकीलाला नियुक्त करा',
    'chat.selectAdvocate': 'वकील निवडा',
    'chat.assigning': 'नियुक्त करत आहे...',
    'chat.assign': 'नियुक्त करा',
    'chat.adminChat': 'एडमिन चॅट',
    'chat.client': 'क्लायंट',
    'chat.advocate': 'वकील',
    'chat.connected': 'जोडले',
    'chat.disconnected': 'डिस्कनेक्ट',
    'chat.noMessagesYet': 'अद्याप कोणतेही संदेश नाही',
    'chat.startConversation': 'संदेश पाठवून संभाषण सुरू करा',
    'chat.typeMessage': 'आपला संदेश टाइप करा...',
    'chat.send': 'पाठवा',
    'chat.uploadFile': 'फाइल अपलोड करा',
    'chat.selected': 'निवडले',
    'chat.uploading': 'अपलोड होत आहे...',
    'chat.upload': 'अपलोड',
    
    // Advocate Chat specific
    'chat.advocateTitle': 'वकील चॅट',
    'chat.viewAllCases': 'सर्व केस पहा',
    'chat.noAssignedCases': 'अद्याप कोणतेही नियुक्त केस नाही',
    'chat.waitForAssignment': 'एडमिनने तुम्हाला केस नियुक्त करण्याची प्रतीक्षा करा',
    
    // Cases page translations
    'cases.assignedCases': 'नियुक्त केस',
    'cases.searchCases': 'केस शोधा...',
    'cases.allStatuses': 'सर्व स्थिती',
    'cases.goToChat': 'चॅटवर जा',
    'cases.caseNumber': 'केस क्रमांक',
    'cases.caseTitle': 'शीर्षक',
    'cases.client': 'क्लायंट',
    'cases.created': 'तयार केले',
    'cases.actions': 'क्रिया',
    'cases.viewDetails': 'तपशील पहा',
    'cases.chat': 'चॅट',
  },
  gu: {
    // Navigation
    'nav.home': 'હોમ',
    'nav.about': 'અમારા વિશે',
    'nav.contact': 'સંપર્ક',
    'nav.userLogin': 'વપરાશકર્તા લોગિન',
    'nav.advocateLogin': 'વકીલ લોગિન',
    'nav.adminLogin': 'એડમિન લોગિન',
    
    // Hero Section
    'hero.title': 'અદ્યતન મધ્યસ્થતા અને કાનૂની કેસ મેનેજમેન્ટ',
    'hero.subtitle': 'AI-ચાલિત સોલ્યુશન્સ સાથે મધ્યસ્થતા અને કાનૂની કેસ મેનેજમેન્ટમાં ક્રાંતિ. ગ્રાહકો, વકીલો અને એડમિનિસ્ટ્રેટર્સને એક વ્યાપક પ્લેટફોર્મમાં જોડો.',
    'hero.getStarted': 'શરૂ કરો',
    'hero.joinAdvocate': 'વકીલ તરીકે જોડાઓ',
    
    // Features
    'features.title': 'શક્તિશાળી સુવિધાઓ',
    'features.caseManagement': 'કેસ મેનેજમેન્ટ',
    'features.caseManagementDesc': 'તમારા બધા કાનૂની બાબતો માટે વ્યાપક કેસ ટ્રેકિંગ અને મેનેજમેન્ટ સિસ્ટમ.',
    'features.roleBased': 'રોલ-આધારિત એક્સેસ',
    'features.roleBasedDesc': 'યોગ્ય પરવાનગીઓ સાથે વપરાશકર્તાઓ, વકીલો અને એડમિનિસ્ટ્રેટર્સ માટે અલગ ડેશબોર્ડ.',
    'features.realtimeChat': 'રિઅલ-ટાઇમ ચેટ',
    'features.realtimeChatDesc': 'ફાઇલ શેરિંગ ક્ષમતાઓ સાથે ગ્રાહકો અને વકીલો વચ્ચે તાત્કાલિક સંચાર.',
    'features.documentManagement': 'ડોક્યુમેન્ટ મેનેજમેન્ટ',
    'features.documentManagementDesc': 'AWS S3 ક્લાઉડ સ્ટોરેજ ઇન્ટિગ્રેશન સાથે સુરક્ષિત ફાઇલ અપલોડ અને મેનેજમેન્ટ.',
    'features.secure': 'સુરક્ષિત અને ખાનગી',
    'features.secureDesc': 'JWT પ્રમાણીકરણ અને એન્ક્રિપ્ટેડ ડેટા સ્ટોરેજ સાથે એન્ટરપ્રાઇઝ-ગ્રેડ સુરક્ષા.',
    'features.analytics': 'વિશ્લેષણ અને અહેવાલો',
    'features.analyticsDesc': 'કેસ પ્રગતિ અને સિસ્ટમ ઇનસાઇટ્સ માટે વ્યાપક અહેવાલ અને વિશ્લેષણ.',
    
    // User Types
    'userTypes.title': 'તમારી ભૂમિકા પસંદ કરો',
    'userTypes.forUsers': 'વપરાશકર્તાઓ માટે',
    'userTypes.forUsersDesc': 'તમારા કાનૂની કેસ સબમિટ કરો અને ટ્રેક કરો',
    'userTypes.forAdvocates': 'વકીલો માટે',
    'userTypes.forAdvocatesDesc': 'નિયુક્ત કેસો અને ગ્રાહકોનું મેનેજમેન્ટ કરો',
    'userTypes.forAdmins': 'એડમિનિસ્ટ્રેટર્સ માટે',
    'userTypes.forAdminsDesc': 'સમગ્ર સિસ્ટમનું નિરીક્ષણ કરો',
    
    // CTA
    'cta.title': 'શરૂ કરવા માટે તૈયાર છો?',
    'cta.subtitle': 'હજારો કાનૂની વ્યવસાયિકોમાં જોડાઓ જે તેમની કેસ મેનેજમેન્ટ જરૂરિયાતો માટે અમારા પ્લેટફોર્મ પર વિશ્વાસ રાખે છે.',
    'cta.startTrial': 'મફત ટ્રાયલ શરૂ કરો',
    'cta.becomeAdvocate': 'વકીલ બનો',
    
    // Footer
    'footer.description': 'AI-ચાલિત સોલ્યુશન્સ અને મલ્ટી-લેંગ્વેજ સપોર્ટ સાથે અદ્યતન મધ્યસ્થતા અને કાનૂની કેસ મેનેજમેન્ટ પ્લેટફોર્મ.',
    'footer.quickLinks': 'ઝડપી લિંક્સ',
    'footer.copyright': '© 2024 ARBITALK. બધા અધિકારો સુરક્ષિત.',
    
    // About Page
    'about.title': 'ARBITALK વિશે',
    'about.subtitle': 'ભારતભર નવીન ટેક્નોલોજી, કૃત્રિમ બુદ્ધિ અને મલ્ટી-લેંગ્વેજ એક્સેસિબિલિટી દ્વારા મધ્યસ્થતા અને કાનૂની કેસ મેનેજમેન્ટમાં ક્રાંતિ.',
    'about.mission': 'અમારું મિશન',
    'about.missionTitle': 'કાનૂની પ્રવેશનું લોકશાહીકરણ',
    'about.missionDesc1': 'ARBITALK ની સ્થાપના ભારતભરના બધાને મધ્યસ્થતા અને કાનૂની કેસ મેનેજમેન્ટ સુલભ બનાવવાના દ્રષ્ટિકોણ સાથે કરવામાં આવી હતી. અમે માનીએ છીએ કે ભાષા અવરોધો અને ટેક્નિકલ જટિલતા ક્યારેય ન્યાય સુધી પહોંચને અવરોધિત ન કરવી જોઈએ.',
    'about.missionDesc2': 'અમારું પ્લેટફોર્મ મધ્યસ્થતા પ્રક્રિયાઓને સુવ્યવસ્થિત કરવા, ખર્ચ ઘટાડવા અને બધા પક્ષોના પરિણામોમાં સુધારો કરવા માટે કટિંગ-એજ AI ટેક્નોલોજીને વપરાશકર્તા-મિત્ર ડિઝાઇન સાથે જોડે છે.',
    
    // Contact Page
    'contact.title': 'ARBITALK સાથે સંપર્ક કરો',
    'contact.subtitle': 'સહાય, પૂછપરછ અથવા અમારા મધ્યસ્થતા અને કાનૂની કેસ મેનેજમેન્ટ પ્લેટફોર્મ વિશે વધુ જાણવા માટે અમારી ટીમ સાથે સંપર્ક કરો.',
    'contact.sendMessage': 'અમને એક સંદેશ મોકલો',
    'contact.fullName': 'પૂર્ણ નામ',
    'contact.email': 'ઇમેઇલ સરનામું',
    'contact.phone': 'ફોન નંબર',
    'contact.userType': 'વપરાશકર્તા પ્રકાર',
    'contact.subject': 'વિષય',
    'contact.message': 'સંદેશ',
    'contact.send': 'સંદેશ મોકલો',
    'contact.sending': 'મોકલી રહ્યા છીએ...',
    
    // Dashboard
    'dashboard.title': 'મારું ડેશબોર્ડ',
    'dashboard.subtitle': 'પાછા સ્વાગત! અહીં તમારા કાનૂની કેસો અને તાજેતરની પ્રવૃત્તિનો અવલોકન છે.',
    'dashboard.totalCases': 'કુલ કેસો',
    'dashboard.activeCases': 'સક્રિય કેસો',
    'dashboard.closedCases': 'બંધ કેસો',
    'dashboard.pendingCases': 'પેન્ડિંગ કેસો',
    'dashboard.recentCases': 'મારા તાજેતરના કેસો',
    'dashboard.viewAllCases': 'બધા કેસો જુઓ',
    'dashboard.caseTitle': 'કેસ શીર્ષક',
    'dashboard.advocate': 'વકીલ',
    'dashboard.status': 'સ્થિતિ',
    'dashboard.priority': 'પ્રાથમિકતા',
    'dashboard.created': 'બનાવ્યું',
    'dashboard.actions': 'ક્રિયાઓ',
    'dashboard.viewDetails': 'વિગતો જુઓ',
    'dashboard.chat': 'ચેટ',
    'dashboard.addCase': 'કેસ ઉમેરો',
    
    // Cases Page
    'cases.title': 'મારા કેસો',
    'cases.search': 'કેસો શોધો...',
    'cases.status': 'સ્થિતિ',
    'cases.type': 'પ્રકાર',
    'cases.priority': 'પ્રાથમિકતા',
    'cases.refresh': 'રિફ્રેશ કરો',
    'cases.noCases': 'કોઈ કેસ મળ્યો નથી',
    'cases.loading': 'કેસો લોડ થઈ રહ્યા છે...',
    
    // Case Details Modal
    'caseDetails.title': 'કેસ વિગતો',
    'caseDetails.caseInformation': 'કેસ માહિતી',
    'caseDetails.caseNumber': 'કેસ નંબર',
    'caseDetails.description': 'વર્ણન',
    'caseDetails.courtName': 'કોર્ટનું નામ',
    'caseDetails.judgeName': 'જજનું નામ',
    'caseDetails.nextHearingDate': 'આગામી સુનાવણીની તારીખ',
    'caseDetails.startDate': 'પ્રારંભ તારીખ',
    'caseDetails.endDate': 'સમાપ્તિ તારીખ',
    'caseDetails.updatedAt': 'અપડેટ કર્યું',
    'caseDetails.financialInformation': 'આર્થિક માહિતી',
    'caseDetails.totalFees': 'કુલ ફી',
    'caseDetails.feesPaid': 'ચૂકવેલ ફી',
    'caseDetails.outstandingAmount': 'બાકી રકમ',
    'caseDetails.disputeInformation': 'વિવાદ માહિતી',
    'caseDetails.requestingParty': 'વિનંતી કરતો પક્ષ',
    'caseDetails.respondent': 'પ્રતિવાદી',
    'caseDetails.disputeDetails': 'વિવાદ વિગતો',
    'caseDetails.name': 'નામ',
    'caseDetails.email': 'ઇમેઇલ',
    'caseDetails.phone': 'ફોન',
    'caseDetails.address': 'સરનામું',
    'caseDetails.relationshipBetweenParties': 'પક્ષો વચ્ચેનો સંબંધ',
    'caseDetails.natureOfDispute': 'વિવાદની પ્રકૃતિ',
    'caseDetails.briefDescription': 'સંક્ષિપ્ત વર્ણન',
    'caseDetails.occurrenceDate': 'ઘટનાની તારીખ',
    'caseDetails.priorCommunication': 'પૂર્વ સંચાર',
    'caseDetails.reliefSought': 'માંગેલી રાહત',
    'caseDetails.monetaryClaim': 'મુદ્રાસ્ફીતિ દાવો',
    'caseDetails.settlement': 'સમજૂતી',
    'caseDetails.otherRelief': 'અન્ય રાહત',
    'caseDetails.otherReliefDetails': 'અન્ય રાહત વિગતો',
    'caseDetails.yes': 'હા',
    'caseDetails.no': 'ના',
    'caseDetails.none': 'કંઈ નહીં',
    'caseDetails.caseTeam': 'કેસ ટીમ',
    'caseDetails.client': 'ક્લાયન્ટ',
    'caseDetails.advocate': 'વકીલ',
    'caseDetails.attachments': 'સંલગ્નક',
    'caseDetails.noAttachments': 'કોઈ સંલગ્નક નથી',
    'caseDetails.close': 'બંધ કરો',
    'caseDetails.chatWithAdvocate': 'વકીલ સાથે ચેટ કરો',
    
    // Create Case Page
    'createCase.title': 'નવો કેસ બનાવો',
    'createCase.disputeResolutionApplication': 'વિવાદ નિરાકરણ અરજી',
    'createCase.caseInformation': 'કેસ માહિતી',
    'createCase.caseTitle': 'કેસ શીર્ષક',
    'createCase.caseDescription': 'કેસ વર્ણન',
    'createCase.requestingParty': 'વિનંતી કરતો પક્ષ',
    'createCase.oppositeParty': 'વિરુદ્ધ પક્ષ (પ્રતિવાદી)',
    'createCase.disputeDetails': 'વિવાદ વિગતો',
    'createCase.fullName': 'વિનંતી કરતા પક્ષનું પૂર્ણ નામ',
    'createCase.email': 'ઇમેઇલ આઈડી',
    'createCase.mobileNumber': 'મોબાઇલ નંબર (વોટ્સએપ પ્રાધાન્ય)',
    'createCase.address': 'નોંધાયેલ વ્યાપારી સરનામું',
    'createCase.fullNameOfOppositeParty': 'વિરુદ્ધ પક્ષનું પૂર્ણ નામ',
    'createCase.contactNumberOfRespondent': 'પ્રતિવાદીનો સંપર્ક નંબર',
    'createCase.emailOfRespondent': 'પ્રતિવાદીનો ઇમેઇલ આઈડી',
    'createCase.addressOfRespondent': 'પ્રતિવાદીનું નોંધાયેલ વ્યાપારી સરનામું',
    'createCase.relationshipBetweenParties': 'પક્ષો વચ્ચેનો સંબંધ',
    'createCase.natureOfDispute': 'વિવાદની પ્રકૃતિ',
    'createCase.client': 'ક્લાયન્ટ',
    'createCase.vendor': 'વિક્રેતા',
    'createCase.businesspartner': 'વ્યાપારી ભાગીદાર',
    'createCase.employee': 'કર્મચારી',
    'createCase.employer': 'નિયોક્તા',
    'createCase.family': 'કુટુંબ',
    'createCase.submit': 'સબમિટ કરો',
    'createCase.submitting': 'સબમિટ કરી રહ્યા છીએ...',
    'createCase.cancel': 'રદ કરો',
    'createCase.caseCreatedSuccessfully': 'કેસ સફળતાપૂર્વક બનાવ્યો',
    
    // Chat Module
    'chat.title': 'કેસ ચેટ',
    'chat.searchCases': 'કેસ શોધો...',
    'chat.status': 'સ્થિતિ',
    'chat.allStatuses': 'બધી સ્થિતિ',
    'chat.open': 'ખુલ્લું',
    'chat.inProgress': 'પ્રગતિમાં',
    'chat.onHold': 'રોકાયેલું',
    'chat.closed': 'બંધ',
    'chat.createNewCase': 'નવો કેસ બનાવો',
    'chat.notAssigned': 'સોંપાયેલ નથી',
    'chat.noCasesFound': 'કોઈ કેસ મળ્યો નથી',
    'chat.noCasesYet': 'હજુ સુધી કોઈ કેસ નથી',
    'chat.tryDifferentSearch': 'વિવિધ શોધ માપદંડ અજમાવો',
    'chat.createFirstCase': 'શરૂ કરવા માટે તમારો પહેલો કેસ બનાવો',
    
    // Admin Chat specific
    'chat.adminTitle': 'એડમિન ચેટ મેનેજમેન્ટ',
    'chat.allAdvocates': 'બધા વકીલો',
    'chat.unassigned': 'સોંપાયેલ નથી',
    'chat.manageCases': 'કેસ મેનેજમેન્ટ',
    'chat.noCasesInSystem': 'હજુ સુધી સિસ્ટમમાં કોઈ કેસ નથી',
    'chat.assignCase': 'કેસ સોંપો',
    'chat.assignCaseTo': 'કેસને વકીલને સોંપો',
    'chat.selectAdvocate': 'વકીલ પસંદ કરો',
    'chat.assigning': 'સોંપી રહ્યા છીએ...',
    'chat.assign': 'સોંપો',
    'chat.adminChat': 'એડમિન ચેટ',
    'chat.client': 'ક્લાયન્ટ',
    'chat.advocate': 'વકીલ',
    'chat.connected': 'જોડાયેલ',
    'chat.disconnected': 'ડિસ્કનેક્ટ',
    'chat.noMessagesYet': 'હજુ સુધી કોઈ સંદેશ નથી',
    'chat.startConversation': 'સંદેશ મોકલીને વાતચીત શરૂ કરો',
    'chat.typeMessage': 'તમારો સંદેશ ટાઇપ કરો...',
    'chat.send': 'મોકલો',
    'chat.uploadFile': 'ફાઇલ અપલોડ કરો',
    'chat.selected': 'પસંદ કર્યું',
    'chat.uploading': 'અપલોડ થઈ રહ્યું છે...',
    'chat.upload': 'અપલોડ',
    
    // Advocate Chat specific
    'chat.advocateTitle': 'વકીલ ચેટ',
    'chat.viewAllCases': 'બધા કેસ જુઓ',
    'chat.noAssignedCases': 'હજુ સુધી કોઈ સોંપાયેલ કેસ નથી',
    'chat.waitForAssignment': 'એડમિન દ્વારા તમને કેસ સોંપવાની રાહ જુઓ',
    
    // Cases page translations
    'cases.assignedCases': 'સોંપાયેલ કેસ',
    'cases.searchCases': 'કેસ શોધો...',
    'cases.allStatuses': 'બધી સ્થિતિ',
    'cases.goToChat': 'ચેટ પર જાઓ',
    'cases.caseNumber': 'કેસ નંબર',
    'cases.caseTitle': 'શીર્ષક',
    'cases.client': 'ક્લાયન્ટ',
    'cases.created': 'બનાવ્યું',
    'cases.actions': 'ક્રિયાઓ',
    'cases.viewDetails': 'વિગતો જુઓ',
    'cases.chat': 'ચેટ',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['en', 'hi', 'mr', 'gu'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
